bot:
  API_KEY: "Nzk5MTM0OTc2NTE1Mzc1MTU0.X__KcQ.qfQdiuOBo7gms4sanOFjzrS7wi0"
  LOAD_COGS: "normal"
#koalabot acc = "NjU0NTgxMjczMDI4ODUzNzcw.XfHoUQ.AYl_OYnkThODtoXePBOXqwDCo4k"
#doorbanger acc = "Nzk5MTM0OTc2NTE1Mzc1MTU0.X__KcQ.qfQdiuOBo7gms4sanOFjzrS7wi0"
music:
  Youtube:
    YoutubeAPIKEY: "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8"
    YoutubeAPIKEY2: "AIzaSyC1rmupwaAB8Q-xaOiPCZCMPnYZ_mJML0Q"
    YoutubeAPIKEY3: "AIzaSyD_31eugYm3WubUF3vT_J8rpI7QazE9mPk"
    YoutubeAPIKEY4: "AIzaSyAtI0bDMqhbiatYfIf7gmj490jiGixcQVw"
    YoutubeAPIKEY5: "AIzaSyACVC_AQzCREQopnO6U-g8bOVTi1pdOpwo"
    YoutubeAPIKEY6: "AIzaSyAoz_H5akWX0z2nQRcmSW_FgPD7BcuWWkM"
    YoutubeAPIKEY7: "AIzaSyAskB97YEIjZSZO84GDuJYn33NMHMqUADo"
  Spotify:
    ClientID: "ac46975af846458ea9f6af6778a8a7cb"
    ClientSecret: "014bfc9a11aa4a5eae8dfcaee5acfac4"
  nodes:
    main:
      host: "139.177.185.11"
      port: 8080
      rest_uri: 'http://139.177.185.11:8080/'
      password: 'youshallnotpass'
      identifier: 'Main-linode-ipv6'
      region: "singapore"
    node3:
      host: "192.53.117.55"
      port: 8080
      rest_uri: 'http://192.53.117.55:8080/'
      password: 'youshallnotpass'
      identifier: 'Linode-ipv6-1'
      region: "singapore"
    # local:
    #   host: "192.168.2.196"
    #   port: 8080
    #   rest_uri: "http://192.168.2.196:8080/"
    #   password: "youshallnotpass"
    #   identifier: "local"
    #   region: "singapore"
    node5:
      host: "172.105.209.143"
      port: 8080
      rest_uri: "http://172.105.209.143:8080/"
      password: "youshallnotpass"
      identifier: "linode-ipv6-japan"
      region: "japan"
spying:
  text_spying_channel: 697347420123561995
  bot_text_spying_channel: 698536354468069427
  member_update_spying_channel: 666142878485053440
  guild_update_spying_channel: 697398841699336192
  connected_voice_channels: 820228681804021760
