bot:
  API_KEY: "Nzk5MTM0OTc2NTE1Mzc1MTU0.X__KcQ.Xwz2VzbVPu2fnQxjsTs7dVHH-Ww"
  LOAD_COGS: "disarmed"

music:
  YoutubeAPIKEY: "AIzaSyCxWtM0W-C-f8erujaPMQiBqK4TuELE-NA"

spying:
  text_spying_channel: 697347420123561995
  bot_text_spying_channel: 698536354468069427
  member_update_spying_channel: 666142878485053440
  guild_update_spying_channel: 697398841699336192
